import { 
    Edit, 
    SimpleForm, 
    TextInput, 
    NumberInput, 
    Labeled, 
    TextField 
} from 'react-admin';

export const ProductEdit = () => (
    /* React-Admin automatically gets the 'id' (which is the slug) from the URL 
       and fetches the record using dataProvider.getOne
    */
    <Edit title="Edit Product">
        <SimpleForm>
            {/* Display ASIN as read-only since it's the unique identifier */}
            <Labeled label="Amazon ASIN">
                <TextField source="asin" />
            </Labeled>

            <TextInput source="title" fullWidth required />
            <NumberInput source="current_price" fullWidth required />
            <TextInput source="currency" fullWidth required />
            <TextInput source="image_url" fullWidth required />
            
            {/* Show the slug but don't allow editing (it's generated by Django) */}
            <Labeled label="Current SEO Slug">
                <TextField source="slug" />
            </Labeled>
        </SimpleForm>
    </Edit>
);